#include "SSP.h"

const char* percussaParamsName [Percussa::sspLast] = {
    "sspEnc1",
    "sspEnc2",
    "sspEnc3",
    "sspEnc4",
    "sspEncSw1",
    "sspEncSw2",
    "sspEncSw3",
    "sspEncSw4",
    "sspSw1",
    "sspSw2",
    "sspSw3",
    "sspSw4",
    "sspSw5",
    "sspSw6",
    "sspSw7",
    "sspSw8",
    "sspSwLeft",
    "sspSwRight",
    "sspSwUp",
    "sspSwDown",
    "sspSwShiftL",
    "sspSwShiftR",
    "sspOutEn1", 
    "sspOutEn2", 
    "sspOutEn3", 
    "sspOutEn4", 
    "sspOutEn5", 
    "sspOutEn6", 
    "sspOutEn7", 
    "sspOutEn8", 
    "sspOutEn9", 
    "sspOutEn10", 
    "sspOutEn11", 
    "sspOutEn12", 
    "sspOutEn13", 
    "sspOutEn14", 
    "sspOutEn15", 
    "sspOutEn16", 
    "sspOutEn17", 
    "sspOutEn18", 
    "sspOutEn19", 
    "sspOutEn20", 
    "sspOutEn21", 
    "sspOutEn22", 
    "sspOutEn23", 
    "sspOutEn24", 
    "sspInEn1", 
    "sspInEn2", 
    "sspInEn3", 
    "sspInEn4", 
    "sspInEn5", 
    "sspInEn6", 
    "sspInEn7", 
    "sspInEn8", 
    "sspInEn9", 
    "sspInEn10", 
    "sspInEn11", 
    "sspInEn12", 
    "sspInEn13", 
    "sspInEn14", 
    "sspInEn15", 
    "sspInEn16", 
    "sspInEn17", 
    "sspInEn18", 
    "sspInEn19", 
    "sspInEn20", 
    "sspInEn21", 
    "sspInEn22", 
    "sspInEn23", 
    "sspInEn24" 
};

const char* percussaParamsText [Percussa::sspLast] = {
    "Encoder 1",
    "Encoder 2",
    "Encoder 3",
    "Encoder 4",
    "Encoder 1 Sw",
    "Encoder 2 Sw",
    "Encoder 3 Sw",
    "Encoder 4 Sw",
    "Button 1",
    "Button 2",
    "Button 3",
    "Button 4",
    "Button 5",
    "Button 6",
    "Button 7",
    "Button 8",
    "Button Left",
    "Button Right",
    "Button Up",
    "Button Down",
    "Button Shift L",
    "Button Shift R",
    "Output Enabled 1", 
    "Output Enabled 2", 
    "Output Enabled 3", 
    "Output Enabled 4", 
    "Output Enabled 5", 
    "Output Enabled 6", 
    "Output Enabled 7", 
    "Output Enabled 8", 
    "Output Enabled 9", 
    "Output Enabled 10", 
    "Output Enabled 11", 
    "Output Enabled 12", 
    "Output Enabled 13", 
    "Output Enabled 14", 
    "Output Enabled 15", 
    "Output Enabled 16", 
    "Output Enabled 17", 
    "Output Enabled 18", 
    "Output Enabled 19", 
    "Output Enabled 20", 
    "Output Enabled 21", 
    "Output Enabled 22", 
    "Output Enabled 23", 
    "Output Enabled 24", 
    "Input Enabled 1", 
    "Input Enabled 2", 
    "Input Enabled 3", 
    "Input Enabled 4", 
    "Input Enabled 5", 
    "Input Enabled 6", 
    "Input Enabled 7", 
    "Input Enabled 8", 
    "Input Enabled 9", 
    "Input Enabled 10", 
    "Input Enabled 11", 
    "Input Enabled 12", 
    "Input Enabled 13", 
    "Input Enabled 14", 
    "Input Enabled 15", 
    "Input Enabled 16", 
    "Input Enabled 17", 
    "Input Enabled 18", 
    "Input Enabled 19", 
    "Input Enabled 20", 
    "Input Enabled 21", 
    "Input Enabled 22", 
    "Input Enabled 23", 
    "Input Enabled 24" 
};